# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Test' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!

  # Pods for Test
  pod 'RxSwift',    '4.1.2'
  pod 'RxCocoa',    '4.1.2'
  pod 'Moya/RxSwift', '11.0.2'
  pod 'Alamofire',  '4.6'
  pod 'ObjectMapper', '3.1'
  pod 'SVProgressHUD', '2.2'
  
end
